[2025-10-15T17:37:44.908+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-15T17:37:44.925+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: game_sentiment_data_pipeline.silver_dbt_gm_rvws_smry manual__2025-10-15T17:36:41.840654+00:00 [queued]>
[2025-10-15T17:37:44.929+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: game_sentiment_data_pipeline.silver_dbt_gm_rvws_smry manual__2025-10-15T17:36:41.840654+00:00 [queued]>
[2025-10-15T17:37:44.930+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-15T17:37:44.938+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): silver_dbt_gm_rvws_smry> on 2025-10-15 17:36:41.840654+00:00
[2025-10-15T17:37:44.941+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=131) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-15T17:37:44.942+0000] {standard_task_runner.py:64} INFO - Started process 132 to run task
[2025-10-15T17:37:44.943+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'game_sentiment_data_pipeline', 'silver_dbt_gm_rvws_smry', 'manual__2025-10-15T17:36:41.840654+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline.py', '--cfg-path', '/tmp/tmpls6zcjss']
[2025-10-15T17:37:44.944+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask silver_dbt_gm_rvws_smry
[2025-10-15T17:37:44.969+0000] {task_command.py:426} INFO - Running <TaskInstance: game_sentiment_data_pipeline.silver_dbt_gm_rvws_smry manual__2025-10-15T17:36:41.840654+00:00 [running]> on host 1a3259f82575
[2025-10-15T17:37:45.015+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='game_sentiment_data_pipeline' AIRFLOW_CTX_TASK_ID='silver_dbt_gm_rvws_smry' AIRFLOW_CTX_EXECUTION_DATE='2025-10-15T17:36:41.840654+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-15T17:36:41.840654+00:00'
[2025-10-15T17:37:45.015+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-15T17:37:46.961+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-15T17:37:46.962+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_pipeline.py", line 33, in run_dbt
    subprocess.run(["dbt","run","--select",f"{model_name}"],check=True)
  File "/usr/local/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dbt', 'run', '--select', 'game_reviews_summary']' returned non-zero exit status 2.
[2025-10-15T17:37:46.970+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=game_sentiment_data_pipeline, task_id=silver_dbt_gm_rvws_smry, run_id=manual__2025-10-15T17:36:41.840654+00:00, execution_date=20251015T173641, start_date=20251015T173744, end_date=20251015T173746
[2025-10-15T17:37:46.980+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 13 for task silver_dbt_gm_rvws_smry (Command '['dbt', 'run', '--select', 'game_reviews_summary']' returned non-zero exit status 2.; 132)
[2025-10-15T17:37:46.987+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-10-15T17:37:47.002+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-15T17:37:47.005+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
