[2025-10-21T19:17:33.514+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-21T19:17:33.525+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: game_sentiment_data_pipeline.sent_analysis manual__2025-10-21T19:15:52.651602+00:00 [queued]>
[2025-10-21T19:17:33.528+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: game_sentiment_data_pipeline.sent_analysis manual__2025-10-21T19:15:52.651602+00:00 [queued]>
[2025-10-21T19:17:33.528+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-21T19:17:33.533+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): sent_analysis> on 2025-10-21 19:15:52.651602+00:00
[2025-10-21T19:17:33.535+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=337) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-21T19:17:33.536+0000] {standard_task_runner.py:64} INFO - Started process 338 to run task
[2025-10-21T19:17:33.536+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'game_sentiment_data_pipeline', 'sent_analysis', 'manual__2025-10-21T19:15:52.651602+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline.py', '--cfg-path', '/tmp/tmpqnj68x5g']
[2025-10-21T19:17:33.537+0000] {standard_task_runner.py:91} INFO - Job 90: Subtask sent_analysis
[2025-10-21T19:17:33.555+0000] {task_command.py:426} INFO - Running <TaskInstance: game_sentiment_data_pipeline.sent_analysis manual__2025-10-21T19:15:52.651602+00:00 [running]> on host 853ab210954c
[2025-10-21T19:17:33.585+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='game_sentiment_data_pipeline' AIRFLOW_CTX_TASK_ID='sent_analysis' AIRFLOW_CTX_EXECUTION_DATE='2025-10-21T19:15:52.651602+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-21T19:15:52.651602+00:00'
[2025-10-21T19:17:33.585+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-21T19:17:33.591+0000] {logging_mixin.py:188} INFO - Invoking Lambda function: sentiment_ntbk
[2025-10-21T19:17:36.954+0000] {logging_mixin.py:188} INFO - Lambda response: {'ResponseMetadata': {'RequestId': 'adbca399-f0f9-442e-826a-22b87bae44a8', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Tue, 21 Oct 2025 19:17:36 GMT', 'content-type': 'application/json', 'content-length': '1489', 'connection': 'keep-alive', 'x-amzn-requestid': 'adbca399-f0f9-442e-826a-22b87bae44a8', 'x-amz-function-error': 'Unhandled', 'x-amzn-remapped-content-length': '0', 'x-amz-executed-version': '$LATEST', 'x-amzn-trace-id': 'Root=1-68f7dc4d-37621f7e29d690821fb96770;Parent=02766548931d793a;Sampled=0;Lineage=1:235f6cb5:0'}, 'RetryAttempts': 0}, 'StatusCode': 200, 'FunctionError': 'Unhandled', 'ExecutedVersion': '$LATEST', 'Payload': <botocore.response.StreamingBody object at 0xffff9e35cf40>}
[2025-10-21T19:17:36.955+0000] {logging_mixin.py:188} INFO - Lambda output: {"errorMessage": "s3://vgsa/silver/silver_tables_dbt_result/games_sentiment_analysis_silver/top_selling_games_reviews/4488e75a-9522-4ad0-9dee-1e3d32d603e0/20251009_143214_00071_275s7_7642792d-3177-448a-b15b-d53156c8d51e", "errorType": "FileNotFoundError", "requestId": "adbca399-f0f9-442e-826a-22b87bae44a8", "stackTrace": ["  File \"/var/task/sentiment_analysis.py\", line 14, in handler\n    df = pd.read_parquet(file_path,filesystem=fs)\n", "  File \"/var/lang/lib/python3.12/site-packages/pandas/io/parquet.py\", line 669, in read_parquet\n    return impl.read(\n", "  File \"/var/lang/lib/python3.12/site-packages/pandas/io/parquet.py\", line 265, in read\n    pa_table = self.api.parquet.read_table(\n", "  File \"/var/lang/lib/python3.12/site-packages/pyarrow/parquet/core.py\", line 1843, in read_table\n    dataset = ParquetDataset(\n", "  File \"/var/lang/lib/python3.12/site-packages/pyarrow/parquet/core.py\", line 1424, in __init__\n    self._dataset = ds.dataset(path_or_paths, filesystem=filesystem,\n", "  File \"/var/lang/lib/python3.12/site-packages/pyarrow/dataset.py\", line 790, in dataset\n    return _filesystem_dataset(source, **kwargs)\n", "  File \"/var/lang/lib/python3.12/site-packages/pyarrow/dataset.py\", line 472, in _filesystem_dataset\n    fs, paths_or_selector = _ensure_single_source(source, filesystem)\n", "  File \"/var/lang/lib/python3.12/site-packages/pyarrow/dataset.py\", line 437, in _ensure_single_source\n    raise FileNotFoundError(path)\n"]}
[2025-10-21T19:17:36.956+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-10-21T19:17:36.956+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-21T19:17:36.965+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=game_sentiment_data_pipeline, task_id=sent_analysis, run_id=manual__2025-10-21T19:15:52.651602+00:00, execution_date=20251021T191552, start_date=20251021T191733, end_date=20251021T191736
[2025-10-21T19:17:36.986+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-10-21T19:17:36.995+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-21T19:17:36.995+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
