[2025-10-21T23:14:13.270+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-21T23:14:13.288+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: game_sentiment_data_pipeline.sent_analysis manual__2025-10-21T23:12:31.197809+00:00 [queued]>
[2025-10-21T23:14:13.293+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: game_sentiment_data_pipeline.sent_analysis manual__2025-10-21T23:12:31.197809+00:00 [queued]>
[2025-10-21T23:14:13.293+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-21T23:14:13.300+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): sent_analysis> on 2025-10-21 23:12:31.197809+00:00
[2025-10-21T23:14:13.304+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=458) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-21T23:14:13.306+0000] {standard_task_runner.py:64} INFO - Started process 459 to run task
[2025-10-21T23:14:13.305+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'game_sentiment_data_pipeline', 'sent_analysis', 'manual__2025-10-21T23:12:31.197809+00:00', '--job-id', '130', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline.py', '--cfg-path', '/tmp/tmpfunyb9k1']
[2025-10-21T23:14:13.307+0000] {standard_task_runner.py:91} INFO - Job 130: Subtask sent_analysis
[2025-10-21T23:14:13.343+0000] {task_command.py:426} INFO - Running <TaskInstance: game_sentiment_data_pipeline.sent_analysis manual__2025-10-21T23:12:31.197809+00:00 [running]> on host 78a5e601f5ac
[2025-10-21T23:14:13.391+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='game_sentiment_data_pipeline' AIRFLOW_CTX_TASK_ID='sent_analysis' AIRFLOW_CTX_EXECUTION_DATE='2025-10-21T23:12:31.197809+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-21T23:12:31.197809+00:00'
[2025-10-21T23:14:13.391+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-21T23:14:13.399+0000] {logging_mixin.py:188} INFO - Invoking Lambda function: sentiment_ntbk
[2025-10-21T23:14:13.591+0000] {logging_mixin.py:188} INFO - Lambda response: {'ResponseMetadata': {'RequestId': 'b09702c4-f054-4af9-bf90-1b8a489e46d6', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Tue, 21 Oct 2025 23:14:13 GMT', 'content-type': 'application/json', 'content-length': '1687', 'connection': 'keep-alive', 'x-amzn-requestid': 'b09702c4-f054-4af9-bf90-1b8a489e46d6', 'x-amz-function-error': 'Unhandled', 'x-amzn-remapped-content-length': '0', 'x-amz-executed-version': '$LATEST', 'x-amzn-trace-id': 'Root=1-68f813c5-65cdfbc72b3e0caf0e2af40a;Parent=2c4ae0d0ddcfe86b;Sampled=0;Lineage=1:235f6cb5:0'}, 'RetryAttempts': 0}, 'StatusCode': 200, 'FunctionError': 'Unhandled', 'ExecutedVersion': '$LATEST', 'Payload': <botocore.response.StreamingBody object at 0xffff9fd54f10>}
[2025-10-21T23:14:13.591+0000] {logging_mixin.py:188} INFO - Lambda output: {"errorMessage": "vgsa/silver/silver_tables_dbt_result/game_reviews/20251021_231352_00087_kkfxg_f441c7be-5383-4dc5-8493-f680fe42d735", "errorType": "FileNotFoundError", "requestId": "b09702c4-f054-4af9-bf90-1b8a489e46d6", "stackTrace": ["  File \"/var/task/sentiment_analysis.py\", line 14, in handler\n    df = pd.read_parquet(file_path,filesystem=fs)\n", "  File \"/var/lang/lib/python3.12/site-packages/pandas/io/parquet.py\", line 669, in read_parquet\n    return impl.read(\n", "  File \"/var/lang/lib/python3.12/site-packages/pandas/io/parquet.py\", line 265, in read\n    pa_table = self.api.parquet.read_table(\n", "  File \"/var/lang/lib/python3.12/site-packages/pyarrow/parquet/core.py\", line 1843, in read_table\n    dataset = ParquetDataset(\n", "  File \"/var/lang/lib/python3.12/site-packages/pyarrow/parquet/core.py\", line 1424, in __init__\n    self._dataset = ds.dataset(path_or_paths, filesystem=filesystem,\n", "  File \"/var/lang/lib/python3.12/site-packages/pyarrow/dataset.py\", line 790, in dataset\n    return _filesystem_dataset(source, **kwargs)\n", "  File \"/var/lang/lib/python3.12/site-packages/pyarrow/dataset.py\", line 482, in _filesystem_dataset\n    return factory.finish(schema)\n", "  File \"pyarrow/_dataset.pyx\", line 3196, in pyarrow._dataset.DatasetFactory.finish\n", "  File \"pyarrow/error.pxi\", line 155, in pyarrow.lib.pyarrow_internal_check_status\n", "  File \"pyarrow/error.pxi\", line 89, in pyarrow.lib.check_status\n", "  File \"pyarrow/_fs.pyx\", line 1583, in pyarrow._fs._cb_open_input_file\n", "  File \"/var/lang/lib/python3.12/site-packages/pyarrow/fs.py\", line 416, in open_input_file\n    raise FileNotFoundError(path)\n"]}
[2025-10-21T23:14:13.591+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-10-21T23:14:13.592+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-21T23:14:13.598+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=game_sentiment_data_pipeline, task_id=sent_analysis, run_id=manual__2025-10-21T23:12:31.197809+00:00, execution_date=20251021T231231, start_date=20251021T231413, end_date=20251021T231413
[2025-10-21T23:14:13.613+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-10-21T23:14:13.627+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-21T23:14:13.628+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
